### PR TITLE
Remove snippets

### PR DESCRIPTION
**Pull request by bioball**
Snippets will be provided by the LSP!

### CODE REVIEW

**Review by stackoverflow — APPROVED** [review]
Snippets are still useful for people who don't use the LSP, but I'm not sure we can disable them dynamically. Something worth investigating.

**Comment by bioball** [comment]
Is there a use-case for _not_ wanting the LSP?

**Comment by stackoverflow** [comment]
> Is there a use-case for not wanting the LSP?

For now, I think only people who don't want/can't install Java 22 in their machines, but this will be fixed once we have a native version.

**Comment by bioball** [comment]
Per our convo earlier: this is somewhat rare of a use-case, and will be rare-er when we build a native executable that doesn't require Java 22, so, probably not worth supporting unless folks ask for it explicitly.

**Pull request merged**
